s(:begin,
  s(:send, nil, :require,
    s(:str, "-test-/bug-5832/bug")),
  s(:class,
    s(:const, nil, :Test_BUG_5832),
    s(:const,
      s(:const,
        s(:const, nil, :Test), :Unit), :TestCase),
    s(:def, :test_block_passing,
      s(:args),
      s(:begin,
        s(:lvasgn, :bug5832,
          s(:str, "[ruby-dev:45071]")),
        s(:lvasgn, :c,
          s(:block,
            s(:send,
              s(:const, nil, :Class), :new),
            s(:args),
            s(:begin,
              s(:block,
                s(:send, nil, :define_method,
                  s(:sym, :call_invoke_block_from_c)),
                s(:args),
                s(:send,
                  s(:const, nil, :Bug), :funcall_callback,
                  s(:self))),
              s(:def, :callback,
                s(:args),
                s(:if,
                  s(:send, nil, :block_given?),
                  s(:yield), nil))))),
        s(:block,
          s(:send, nil, :assert_nothing_raised,
            s(:const, nil, :RuntimeError),
            s(:lvar, :bug5832)),
          s(:args),
          s(:block,
            s(:send,
              s(:send,
                s(:lvar, :c), :new), :call_invoke_block_from_c),
            s(:args),
            s(:send, nil, :raise,
              s(:str, "unreachable"))))))))
