s(:begin,
  s(:send, nil, :require,
    s(:str, "test/unit")),
  s(:class,
    s(:const, nil, :Test_BUG_3571),
    s(:const,
      s(:const,
        s(:const, nil, :Test), :Unit), :TestCase),
    s(:def, :test_block_call_id,
      s(:args),
      s(:begin,
        s(:lvasgn, :bug3571,
          s(:str, "[ruby-dev:41852]")),
        s(:lvasgn, :src,
          s(:dstr,
            s(:str, "begin\n"),
            s(:str, "  Bug.start\n"),
            s(:str, "rescue NotImplementedError => e\n"),
            s(:str, "  STDERR.puts e.message, e.backtrace[$0.size..-1]\n"),
            s(:str, "end\n"))),
        s(:lvasgn, :out,
          s(:array,
            s(:str, "start() function is unimplemented on this machine"),
            s(:str, "-:2:in `start'"),
            s(:str, "-:2:in `<main>'"))),
        s(:send, nil, :assert_in_out_err,
          s(:array,
            s(:str, "-r-test-/bug-3571/bug")),
          s(:lvar, :src),
          s(:array),
          s(:lvar, :out),
          s(:lvar, :bug3571))))))
